### ISSUE TITLE
Missing value for "result" in case of Invalid method.

### ISSUE THREAD

**Issue by yawor** [gatt-ip/gatt-ip-android#3]
I've found an error in `GATTIP.sendResponse` method. It unconditionally tries to retrieve `Constants.kResult` value from `jsonData` param, but for invalid message error, there's no such key added to the data, causing an exception and no response to the client. It also crashes the reference app with following exception:

> 06-24 12:10:55.878 15761 17312 V GATTIPServer: request message: {"jsonrpc":"2.0","method":"ScanForPeripherals","params":{},"id":"3"}
> 06-24 12:10:55.882 15761 17316 D org.gatt_ip.GATTIP: Processing GATT-IP request.
> 06-24 12:10:56.004 15761 17316 E AndroidRuntime: FATAL EXCEPTION: Thread-4114
> 06-24 12:10:56.004 15761 17316 E AndroidRuntime: Process: org.gatt_ip.activity, PID: 15761
> 06-24 12:10:56.004 15761 17316 E AndroidRuntime: java.lang.RuntimeException: org.json.JSONException: No value for result
> 06-24 12:10:56.004 15761 17316 E AndroidRuntime:  at org.gatt_ip.GATTIP$1.run(GATTIP.java:115)
> 06-24 12:10:56.004 15761 17316 E AndroidRuntime: Caused by: org.json.JSONException: No value for result
> 06-24 12:10:56.004 15761 17316 E AndroidRuntime:  at org.json.JSONObject.get(JSONObject.java:389)
> 06-24 12:10:56.004 15761 17316 E AndroidRuntime:  at org.json.JSONObject.getString(JSONObject.java:550)
> 06-24 12:10:56.004 15761 17316 E AndroidRuntime:  at org.gatt_ip.GATTIP.sendResponse(GATTIP.java:191)
> 06-24 12:10:56.004 15761 17316 E AndroidRuntime:  at org.gatt_ip.GATTIP.sendResponse(GATTIP.java:209)
> 06-24 12:10:56.004 15761 17316 E AndroidRuntime:  at org.gatt_ip.GATTIP.processRequest(GATTIP.java:292)
> 06-24 12:10:56.004 15761 17316 E AndroidRuntime:  at org.gatt_ip.GATTIP.access$100(GATTIP.java:28)
> 06-24 12:10:56.004 15761 17316 E AndroidRuntime:  at org.gatt_ip.GATTIP$1.run(GATTIP.java:112)
> 06-24 12:10:56.005   779   790 W ActivityManager:   Force finishing activity org.gatt_ip.activity/org.gatt_ip.app.RemoteGATTIPActivity

The solution would be to either add proper `Constants.kResult` key to the data in `GATTIP.processRequest` method or add check if the key exists in the `GATTIP.sendResponse` method.

**Comment by Kushi171987** [comment]
Thanks for concern about the issue @yawor . We found it & fixed in the dev build.

Thanks again :)

**Comment by Kushi171987** [comment]
Fixed it.
